language: node_js
node_js:
  - "6.9"
script:
  - echo "Deploy firebase"
install:
  - npm install -g firebase-tools
  - npm install
  - npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
